Repository Rookout/explorook, pull requests merged in 2018-12, with the labels that each got.

#18 Undo shit
  .circleci/config.yml
  README.md
  package-lock.json
  package.json
  src/webapp/package.json
  src/webapp/yarn.lock
  yarn.lock
Labels: bug

#21 RK-546 - Allow headless mode to run multiple repos by passing a json array
  src/headless.ts
Labels: DeployEnforcer/MergeOnceApproved

#19 upgrade webapp "vulnerable" dependencies
  package.json
  src/webapp/package.json
  src/webapp/yarn.lock
Labels: enhancement, security

#20 RK-233 agnostic repository id
  package-lock.json
  package.json
  src/prase-repo.d.ts
  src/rep-store.ts
Labels: bug

#24 RK-673 Better call to action
  index-worker.html
  package.json
  src/webapp/public/folders.svg
  src/webapp/src/App.css
  src/webapp/src/components/ReposList.js
Labels: enhancement

#25 RK-738 - supress legit git error
  package.json
  src/git.ts
Labels: DeployEnforcer/MergeOnceApproved, bug

#26 RK-740 logging graphql errors to sentry
  package-lock.json
  package.json
  src/api.ts
  src/middlewares.ts
  src/server.ts
Labels: DeployEnforcer/MergeOnceApproved, enhancement
