Repository Rookout/explorook, pull requests merged in 2019-01, with the labels that each got.

#27 RK-837 - new eula
  package-lock.json
  package.json
  src/webapp/public/eula.v2.html
  src/webapp/src/components/EulaModal.js
Labels: DeployEnforcer/MergeOnceApproved, enhancement

#30 RK-819 Allow adding repo from api request
  graphql/schema.graphql
  package.json
  src/api.ts
  src/headless.ts
  src/index-worker.ts
  src/server.ts
  src/webapp/src/components/ReposList.js
Labels: enhancement

#31 RK-867 Add branch to repo ID in case this repo was already added
  package-lock.json
  package.json
  src/git.ts
  src/rep-store.ts
Labels: DeployEnforcer/MergeOnceApproved

#29 RK-915 - Auth dont fail cors requests
  package.json
  src/server.ts
Labels: DeployEnforcer/MergeOnceApproved, bug

#32 RK-817 Added the ability to pass the token directly to FE
  package-lock.json
  package.json
  src/middlewares.ts
  src/server.ts
Labels: enhancement

#33 RK-974 - invalidate homebrew cache as it is faulty and fails builds
  .circleci/config.yml
Labels: DeployEnforcer/MergeOnceApproved

#34 RK-975 - homebrew fails to install wine in CI/CD pipeling
  .circleci/config.yml
Labels: DeployEnforcer/MergeOnceApproved

#38 RK-1040 - Fix chrome open macos
  package-lock.json
  package.json
  src/chrome-opn.d.ts
  src/middlewares.ts
Labels: DeployEnforcer/MergeOnceApproved, enhancement

#37 RK-764 warn non git repos
  package.json
  src/api.ts
  src/fsIndexer.ts
  src/git.ts
  src/headless.ts
  src/index-worker.ts
  src/index.ts
  src/mem-store.ts
  src/middlewares.ts
  src/parseRepo.d.ts
  src/repoStore.ts
  src/server.ts
  src/webapp/craco.config.js
  src/webapp/package.json
  src/webapp/src/App.js
  src/webapp/src/components/Checkbox.js
  src/webapp/src/components/ConfirmModal.js
  src/webapp/src/components/EulaModal.js
  src/webapp/src/components/Footer.js
  src/webapp/src/components/Header.js
  src/webapp/src/components/RepoListItem.js
  src/webapp/src/components/ReposList.js
  src/webapp/src/components/Token.js
  src/webapp/src/index.js
  src/webapp/yarn.lock
Labels: DeployEnforcer/MergeOnceApproved, feature

#42 RK-1148 - fix windows slashes in inner folders
  package.json
  src/git.ts
Labels: DeployEnforcer/MergeOnceApproved, bug

#44 created yarn.lock from previous working package-lock.json
  yarn.lock
Labels: DeployEnforcer/MergeOnceApproved, bug
