Repository Rookout/explorook, pull requests merged in 2019-07, with the labels that each got.

#81 Add link to security page RK-3014
  README.md
Labels: DeployEnforcer/MergeOnceApproved

#92 RK-3307 - ignore the check for readonly volumes in linux
  src/index.ts
Labels: bug

#88 RK-3926 Hedwig/security updates
  package.json
  src/webapp/package.json
  src/webapp/yarn.lock
  yarn.lock
Labels: security

#93 RK-3313 - version bump
  package.json
Labels: DeployEnforcer/MergeOnceApproved
